language: ruby
cache: bundler
rvm:
- 2.0.0
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database chess_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: nP9gurU92Ir8iut2cEYgeRizFw0wGWEEJ8Yy05Yfp5UTGp9b9MRM7gOuejBx3p8bF3BquxDWbjUEXoYfWU+cWZ1yAfYmr7sqUAFwmHwjrPyBlFCxwXQNefyhINdIAGiYwhZXCvcI05oMha3PQePZXwO4A3NphjoMLt+LyS4dnNM=
  app: fischer-chess
  on:
    repo: Team-Fischer/chess
